so_luong_sach = input("Nhập số lượng sách: ")
ma_sach = input("Nhập mã sách: ")
ten_sach = input("Nhập tên sách: ")
tac_gia = input("Nhập tên tác giá: ")
nam_xuat_ban = input("Nhập năm xuất bản: ")
print(f"Thư viện ĐHKTKTCN có {so_luong_sach} sách {ten_sach} với mã số {ma_sach}. Cuốn sách của tác giả {tac_gia} được xuất bản vào năm {nam_xuat_ban}")
